[package]
name = "NftContract"
version = "1.0.0"
authors = []

[addresses]
nft_contract = "" 

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
