[package]
name = "movement move compile"
version = "1.0.0"
authors = []

[addresses]
counter_movement = "" 

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
